#!/bin/sh

set -e

progname=$(basename "$0")

print_help()
{
    printf "usage: %s syn | kjv\n" "$progname"
}

if [ $# -gt 1 ]
then
    printf "%s: only 1 argument is accepted\n" "$progname" >&2
    print_help
    exit 1
elif [ $# -eq 0 ]
then
    print_help
    exit 0
fi

bible=$1

case $bible in
    syn | kjv)
        python3 formatter.py "txt/$bible.txt" | less -M
        ;;
    *)
        printf "%s: invalid bible: %s\n" "$progname" "$bible" >&2
        print_help
        exit 1
        ;;
esac
